# SPDX-FileCopyrightText: 2026 The Snelleutf Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

amalgamate:
	python3 simdutf/singleheader/amalgamate.py --no-zip --no-readme --output-dir simdutf/build
	cp simdutf/build/simdutf.cpp simdutf/build/simdutf.h simdutf/build/simdutf_c.h src/
