# SPDX-FileCopyrightText: 2026 The Chaste Authors
# SPDX-License-Identifier: CC0-1.0

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  reuse:
    image: fsfe/reuse:6
    commands:
      - reuse lint
